module.exports = {
    stevenText: "Steven is the son of Greg Universe and Rose Quartz. He is the only half-human, half-gem and has special powers.",
    stevenPic: "https://i.cdn.turner.com/v5cache/CARTOON/site/Images/i79/steven_steven_180x180.png",
    stevenUri: "https://fantendo.wikia.com/wiki/Steven_Universe",
    garnetText: "Garnet is a fusion of the gems Ruby and Sapphire. She is the protector of the group. Also known as 'Square Mom'.",
    garnetPic: "https://vignette2.wikia.nocookie.net/steven-universe/images/9/9a/NewGarnetPose.png/revision/latest/scale-to-width/180?cb=20150504221901",
    garnetUri: "https://steven-universe.wikia.com/wiki/Garnet",
    pearlText: "Pearl is the salty, hopeless space lesbian. She was deeply in love with Steven's mom and will protect Steven at all costs. Also known as 'Bird Mom'.",
    pearlPic: "https://static.tvtropes.org/pmwiki/pub/images/pearl_ii_6893.png",
    pearlUri: "https://steven-universe.wikia.com/wiki/Pearl",
    lapisText: "Lapis is a Homeoworld gem who was trapped in a mirror during the wars over earth. She is a precious cinomin roll.",
    lapisPic: "https://vignette2.wikia.nocookie.net/steven-universe/images/6/6c/Lapis(1).png/revision/latest?cb=20150321125218",
    lapisUri: "https://steven-universe.wikia.com/wiki/Lapis",
    peridotText: "Peridot was once a threat to the Crystal Gem, but she is now a Crystal Gem herself. Her favorite word is 'CLOD'.",
    peridotPic: "https://vignette1.wikia.nocookie.net/villains/images/0/0e/PeridotNoLimbs.png/revision/latest/scale-to-width-down/250?cb=20150925014545",
    peridotUri: "https://steven-universe.wikia.com/wiki/Peridot",
    amethystText: "Amethyst is a gem that was made on Earth. She hates herself, but that makes her try harder to be adiquite. She is kind and a good friend.",
    amythystPic: "https://img2.wikia.nocookie.net/__cb20131220051809/steven-universe/images/8/8d/Steven_amethyst_174x252.png",
    amethystUri: "https://steven-universe.wikia.com/wiki/Amethyst",
    connieText: "Connie is Steven's best friend. She's smart, she used to have glasses but Steven healed her. She is a human.",
    conniePic: "https://vignette4.wikia.nocookie.net/steven-universe/images/f/f9/Connie_Maheswaran.png/revision/latest/scale-to-width/2500?cb=20141222014431",
    connieUri: "https://steven-universe.wikia.com/wiki/Connie",
    sadieText: "Sadie works at the Big Donut, she is a good friend of Steven's.", 
    sadiePic: "https://img2.wikia.nocookie.net/__cb20140222131642/stevenuniverse/es/images/2/2b/Sadie.png",
    sadieUri: "https://steven-universe.wikia.com/Sadie",
    larsText: "Lars pretends to be hardcore and cool, but deep down he is a big softy. He secretly-not-so-secretly loves Sadie.",
    larsPic: "https://img2.wikia.nocookie.net/__cb20140224000616/villains/images/b/bf/Steven_lars_174x252.png",
    larsUri: "https://steven-universe.wikia.com/wiki/Lars",
    gregText: "Greg is Steven's dad. he owns a car wash, and is just recently a billionare.",
    gregPic: "https://vignette1.wikia.nocookie.net/steven-universe/images/9/92/Greg_PantsCut.png/revision/latest?cb=20141224171314",
    gregUri: "https://steven-universe.wikia.com/wiki/Greg"
};
